apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: container-sftp-2
      image: atmoz/sftp
      volumeMounts:
        - mountPath: /etc/sftp/
          name: sftp-configmap
          readOnly: true
          ports:
            - containerPort: 22
              name: ssh
              protocol: TCP
  volumes: 
    - name: sftp-configmap
      persistentVolumeClaim:
        ClainName: pvc-1